# -*- restclient -*-
# Requests for REST Client mode in emacs

GET http://localhost:3000
Authorization: 123456qwerty

# GET all coffees
GET http://localhost:3000/coffees
Authorization: 123456qwerty

# Get single coffee
GET http://localhost:3000/coffees/-1

# Post a coffee
POST http://localhost:3000/coffees
Content-Type: application/json

{
"name": "Coffee #4",
"brand": "Nest",
"flavors": ["caramel", "chocolate"]
}

# Patch a coffee
PATCH http://localhost:3000/coffees/1
Content-Type: application/json
{
"name": "Shipwreck Roast"
}

#Delete a coffee
DELETE http://localhost:3000/coffees/1
