# -*- restclient -*-
# Requests for REST Client mode in emacs

GET http://localhost:3000

# GET all coffees
GET http://localhost:3000/coffees

# Get single coffee
GET http://localhost:3000/coffees/655a625aa51e5c2735890dc3

# Post a coffee
POST http://localhost:3000/coffees
Content-Type: application/json

{
"name": "New Florida Roast",
"brand": "Kawcia od Pawcia",
"flavors": ["chocolate", "raspberry"]
}

# Patch a coffee
PATCH http://localhost:3000/coffees/655a629aa51e5c2735890dc7
Content-Type: application/json
{
"name": "Kawa miesiąca"
}

#Delete a coffee
DELETE http://localhost:3000/coffees/655a629aa51e5c2735890dc7
